### ISSUE TITLE
May I ask how to compile it

### ISSUE THREAD

**Issue by LECYWZA** [underdog54/android_kernel_samsung_gts9wifi#2]
export ARCH=arm64
export SUBARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
make O=out defconfig
make O=out -j$(nproc) CC=clang CFLAGS="--std=gnu90"

Hello, please advise, how do I compile it, I compile it with your source code, and the Image is converted to boot.img, and it will restart in an infinite loop when you flash it

**Comment by underdog54** [comment]
Sorry for the late response. Unfortunately, I am no longer building kernels that often that much anymore. I will just be maintaining them now.
